check50:
  files:
    - !exclude "*"
    - !require U1.c
    - !require U1rez.txt
    - !require programa.cpp

lab50:
  files:
    - !exclude "*"
    - !include "programa.cpp"
    - !include "U1.txt"

submit50:
  files:
    - !exclude "*"
    - !include "programa.cpp"
